### ISSUE TITLE
Do not allow 't' and 'amount' parameters in the same URI

### ISSUE THREAD

**Issue by jonas-lundqvist** [bitjson/chip-paypro#2]
From the Telegram group:

I think the validation should produce an error if both `t` and `amount` are present in the same URI. If a token aware wallet is requesting a specific BCH amount and needs backwards compatibility that wallet should drop the `t` parameter since that request obviously can't contain tokens.

**Comment by bitjson** [comment]
Thanks for opening the issue! Agreed: this would almost certainly be an implementation bug, and clients should [error as strictly as possible to maximize future upgrade possibilities](https://github.com/bitjson/chip-paypro#design-of-payment-uri-error-behavior).

Fixed in https://github.com/bitjson/chip-paypro/commit/68f0f270dcc034cbf5f818e9357684fa2843aa20 🚀
